# Generated by Django 4.2.5 on 2025-01-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HiringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_no', models.PositiveIntegerField()),
                ('department', models.CharField(choices=[('Finance & Accounts', 'Finance & Accounts'), ('Appliance Division', 'Appliance Division'), ('Brand & Communications', 'Brand & Communications'), ('Category Strategy and Go to Market', 'Category Strategy and Go to Market'), ('Civil & MEP', 'Civil & MEP'), ('Corporate Manufacturing Services', 'Corporate Manufacturing Services'), ('Customer Service', 'Customer Service'), ('Digital & Emerging Channels', 'Digital & Emerging Channels'), ('Electronics Division', 'Electronics Division'), ('Human Resources', 'Human Resources'), ('Marketing', 'Marketing'), ('Mechanical & Electronics Division', 'Mechanical & Electronics Division'), ('Quality', 'Quality'), ('R&D (Electronics Divn)', 'R&D (Electronics Divn)'), ('Strategy', 'Strategy'), ('Sunflame', 'Sunflame'), ('Supply Chain Management', 'Supply Chain Management'), ('Systems', 'Systems'), ('Wires & Cables Divn', 'Wires & Cables Divn')], max_length=255)),
                ('vacancy_title', models.CharField(max_length=255)),
                ('recruiter', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('Naukri', 'Naukri'), ('Linkedin', 'Linkedin'), ('Employee Referrals', 'Employee Referrals'), ('IIM Jobs', 'IIM Jobs'), ('Others', 'Others')], max_length=255)),
                ('location', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Bangalore', 'Bangalore'), ('Bhopal', 'Bhopal'), ('Bhubhaneshwar', 'Bhubhaneshwar'), ('Chandigarh', 'Chandigarh'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Delhi', 'Delhi'), ('Faridabad', 'Faridabad'), ('Gurugram', 'Gurugram'), ('Hyderabad', 'Hyderabad'), ('Indore', 'Indore'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Others', 'Others')], max_length=255)),
                ('place_of_posting', models.CharField(max_length=255)),
                ('no_of_hires', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('J', 'Junior'), ('E', 'Executive'), ('O', 'Officer'), ('M', 'Manager'), ('C', 'Chief')], max_length=1)),
                ('type_hire', models.CharField(choices=[('New Hire', 'New Hire'), ('Replacement', 'Replacement')], max_length=20)),
                ('date_req_received', models.DateField()),
                ('date_deltek_post', models.DateField()),
                ('date_round1_cvsent', models.DateField()),
                ('date_revert1', models.DateField()),
                ('date_candidate_finalised', models.DateField()),
                ('cv_given', models.PositiveIntegerField()),
                ('cv_shared', models.PositiveIntegerField()),
                ('cv_shortlisted', models.PositiveIntegerField()),
                ('candidates_interviewed', models.PositiveIntegerField()),
                ('candidates_finalround', models.PositiveIntegerField()),
                ('no_of_offers', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Candidate Finalized', 'Candidate Finalized'), ('CVs shared', 'CVs shared'), ('CVs to be shared', 'CVs to be shared'), ('More CVs required', 'More CVs required'), ('Interview', 'Interview'), ('On Hold', 'On Hold'), ('On Hold (New Hire)', 'On Hold (New Hire)')], max_length=255)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
