# Generated by Django 4.2.5 on 2025-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringdata',
            name='candidates_finalround',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='candidates_interviewed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='cv_given',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='cv_shared',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='cv_shortlisted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='date_candidate_finalised',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='date_deltek_post',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='date_req_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='date_revert1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='date_round1_cvsent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='indent_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='location',
            field=models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Bangalore', 'Bangalore'), ('Bhopal', 'Bhopal'), ('Bhubhaneshwar', 'Bhubhaneshwar'), ('Chandigarh', 'Chandigarh'), ('Chavady Factory', 'Chavady Factory'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Dehradun', 'Dehradun'), ('Delhi', 'Delhi'), ('Faridabad', 'Faridabad'), ('Ghaziabad', 'Ghaziabad'), ('Ghaziabad Lab', 'Ghaziabad Lab'), ('Gurugram', 'Gurugram'), ('Gurugram Corporate', 'Gurugram Corporate'), ('Gurugram SB', 'Gurugram SB'), ('GUTS Haridwar', 'GUTS Haridwar'), ('GUTS Hyderabad', 'GUTS Hyderabad'), ('Guwahati', 'Guwahati'), ('Haridwar', 'Haridwar'), ('Hubli', 'Hubli'), ('Hyderabad', 'Hyderabad'), ('Indore', 'Indore'), ('Jaipur', 'Jaipur'), ('Jammu', 'Jammu'), ('Jodhpur', 'Jodhpur'), ('Kanpur', 'Kanpur'), ('Kashipur Factory', 'Kashipur Factory'), ('Kashmir', 'Kashmir'), ('Kochi Corporate', 'Kochi Corporate'), ('Kochi R&D', 'Kochi R&D'), ('Kochi R&D Dsir', 'Kochi R&D Dsir'), ('Kolkata', 'Kolkata'), ('Lucknow', 'Lucknow'), ('Ludhiana', 'Ludhiana'), ('Madurai', 'Madurai'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Patna', 'Patna'), ('Perundurai', 'Perundurai'), ('Pune', 'Pune'), ('Raipur', 'Raipur'), ('Ranchi', 'Ranchi'), ('Roorkee Factory', 'Roorkee Factory'), ('Sikkim Unit 2', 'Sikkim Unit 2'), ('Sikkim Unit 3', 'Sikkim Unit 3'), ('Srinagar', 'Srinagar'), ('Udupi', 'Udupi'), ('VCPL Patnagar', 'VCPL Patnagar'), ('Vijayawada', 'Vijayawada'), ('Others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='no_of_hires',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='no_of_offers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
