# Generated by Django 4.2.5 on 2025-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_alter_hiringdata_candidates_finalround_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringdata',
            name='indent_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
