# Generated by Django 4.2.5 on 2025-02-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_hiringdata_indent_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='indent_no',
            field=models.CharField(max_length=255),
        ),
    ]
