# Generated by Django 4.2.5 on 2025-03-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0004_hiringdata_updated_at_alter_hiringdata_indent_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringdata',
            name='date_req_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='date_round1_cvsent',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='no_of_hires',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='place_of_posting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdata',
            name='source',
            field=models.CharField(blank=True, choices=[('Naukri', 'Naukri'), ('Linkedin', 'Linkedin'), ('Employee Referrals', 'Employee Referrals'), ('IIM Jobs', 'IIM Jobs'), ('Others', 'Others')], max_length=255, null=True),
        ),
    ]
