# Generated by Django 4.2.5 on 2025-04-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_rename_no_of_hires_hiringdata_no_of_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
