# Generated by Django 4.2.5 on 2025-04-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0007_recruitmentfunnel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecruitmentFunnel',
        ),
    ]
