# Generated by Django 4.2.5 on 2025-04-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0008_delete_recruitmentfunnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringdata',
            name='status',
            field=models.CharField(choices=[('Candidate Finalized', 'Candidate Finalized'), ('CVs shared', 'CVs shared'), ('CVs to be shared', 'CVs to be shared'), ('More CVs required', 'More CVs required'), ('Interview', 'Interview'), ('On Hold', 'On Hold'), ('On Hold (New Hire)', 'On Hold (New Hire)'), ('Hired', 'Hired')], max_length=255),
        ),
    ]
